#  CODE FOR IMAGE MANIPULATIONS (Convolutions - Blurring and Sharpening) 

In [1]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import cv2

In [2]:
image = cv2.imread("Self_Driving_Car.jpg")
cv2.imshow("Self Driving Car", image)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
image.shape


(426, 640, 3)

# gray

In [6]:
gray_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("Self Driving Car in gray", gray_img)
cv2.waitKey()
cv2.destroyAllWindows()


# apply sharpening kernel

In [13]:
#1
#Sharp_Kernel = np.array([[0,-1,0],
#                       [-1,5,-1],
#                       [0,-1,0]])

#2
Sharp_Kernel = np.array([[-1,-1,-1],
                       [-1,9,-1],
                       [-1,-1,-1]])

Sharpened_image = cv2.filter2D(gray_img, -1, Sharp_Kernel)

In [12]:
cv2.imshow("Sharpened Image", Sharpened_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# apply blurring kernel

In [14]:
Blur_kernel = np.ones((3,3))
Blur_kernel

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
Blurred_image = cv2.filter2D(gray_img, -1, Blur_kernel)

In [18]:
cv2.imshow("Blurred Image", Blurred_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### blurring kernel normalized

In [19]:
Blur_kernel = np.ones((3,3))*(1/9)
Blur_kernel

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [20]:
Blurred_image = cv2.filter2D(gray_img, -1, Blur_kernel)

In [21]:
cv2.imshow("Blurred Image Normalized", Blurred_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### larger kernel matrix

In [22]:
Blur_kernel = np.ones((8,8))*(1/64)
Blur_kernel

array([[0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625]])

In [35]:
Blurred_image = cv2.filter2D(gray_img, -1, Blur_kernel)

In [36]:
cv2.imshow("Blurred Image Normalized", Blurred_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
cv2.imwrite("saving_blur_image.jpg", Blurred_image)

True

## sharpen the blurred image

In [59]:
blurimg = cv2.imread("saving_blur_image.jpg")

In [69]:
Sharp_Kernel = np.array([[-1,-1,-1],
                       [-1,15,-1],
                       [-1,-1,-1]])

In [70]:
Blur2Sharp = cv2.filter2D(blurimg, -1, Sharp_Kernel)

In [71]:
cv2.imshow("Blurred Image Sharpened", Blur2Sharp)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [72]:
# not wokring as I thought :D :D :D